### ISSUE TITLE
Qt: Untested Windows version 10.0 detected!

### ISSUE THREAD

**Issue by shahidul-brur** [Eronana/CodeforcesCrawler#2]
I am a windows 10 user. When I try to use the tool, it gives the following error after crawling the html before starting to convert them to pdf:

`Qt: Untested Windows version 10.0 detected!`
`QPainter::begin(): Returned false`
`Exit with code 1 due to network error: ContentNotFoundError`

How to fix it?

**Comment by ccinv** [comment]
I am also a Windows10 user but things turn out to be fine.
Could you report your version by `wkhtmltopdf -V`?

**Comment by ccinv** [comment]
And if you just want to get PDFs.Check it out:[CodeforcesPDF](https://github.com/Eronana/CodeforcesPDF).
I've made them up to date.

**Comment by shahidul-brur** [comment]
wkhtmltopdf 0.9.9

**Comment by ccinv** [comment]
Untested Windows 10 is not the main problem.It should be dealt with by wkhtmltopdf developers.
As for `ContentNotFoundError`,a likely reason is there is something missing in `caches` or `src`.
