### ISSUE TITLE
Downloaded pdf files are not latex formatted.

### ISSUE THREAD

**Issue by shahidul-brur** [Eronana/CodeforcesCrawler#4]
The downloaded pdf files doesn't follow latex format. Rather the files are showing latex command as text.
Here is a screenshot from pdf for contest id 1000
![Here is a screenshot from pdf for contest id 1000](https://user-images.githubusercontent.com/15035339/51933185-ecb4a980-242a-11e9-9579-5bc5f9570677.JPG)

**Comment by ccinv** [comment]
Mathjax is good now. Btw, output pdfs are larger because of allowing javascripts.
